# Generated by Django 5.2.1 on 2025-05-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('site', models.CharField(default='none', max_length=100)),
                ('title', models.CharField(default='none', max_length=200)),
                ('company', models.CharField(default='none', max_length=200)),
                ('date_posted', models.DateField(blank=True, default=None, null=True)),
                ('description', models.TextField(default='none')),
                ('location', models.CharField(default='none', max_length=200)),
                ('keywords', models.CharField(default='none')),
                ('link', models.CharField(default='none')),
            ],
        ),
    ]
