# Generated by Django 5.2.1 on 2025-05-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobHunt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='description',
            field=models.TextField(default='none'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='company',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='site',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='title',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
