# Generated by Django 5.2.1 on 2025-05-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobHunt', '0002_jobpost_description_alter_jobpost_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='date_posted',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
