# Generated by Django 5.2.1 on 2025-05-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobHunt', '0003_alter_jobpost_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='location',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
