# Generated by Django 5.2.1 on 2025-05-14 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobHunt', '0004_jobpost_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='date_posted',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
