# Generated by Django 5.2.1 on 2025-05-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobHunt', '0005_alter_jobpost_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='keywords',
            field=models.CharField(default='none'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='link',
            field=models.CharField(default='none'),
        ),
    ]
